In [66]:
import numpy as np
import pandas as pd
import plotly.express as px

# Data Loading

In [67]:
df = pd.read_csv('asylum_seekers.csv')
df

C:\Users\star 1\AppData\Local\Temp\ipykernel_10484\463960375.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('asylum_seekers.csv')

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5.0,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186.0,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250.0,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273.0,150,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129715,2016,United States of America,Zimbabwe,G / IN,232,NaN,229,16,NaN,*,10,28,435,NaN
129716,2016,United States of America,Zimbabwe,G / EO,142,NaN,12,*,NaN,*,23,31,138,NaN
129717,2016,South Africa,Zimbabwe,G / AR,94,9,NaN,NaN,NaN,NaN,94,94,0,NaN
129718,2016,South Africa,Zimbabwe,G / FI,41238,4124,7964,73,NaN,7869,NaN,7942,41260,NaN
129719,2016,Zambia,Zimbabwe,G / FI,*,*,*,0,NaN,*,*,*,*,*

# Data Understanding

##  Column Descriptions

| # | Column Name | Description | Data Type | Example / Notes |
|---|---|---|---|---|
| 1 | `Year` | The year in which the asylum-seeker statistics were recorded. | Integer | 2000, 2001, 2020, etc. |
| 2 | `Country / territory of asylum/residence` | The country or territory where the asylum seeker submitted their claim or resides while seeking asylum. | Categorical | Egypt, Germany, France, etc. |
| 3 | `Origin` | The country or territory of origin/nationality of the asylum seeker. | Categorical | Sudan, Syria, Afghanistan, etc. |
| 4 | `RSD procedure type / level` | The type or level of Refugee Status Determination (RSD) procedure used to process the asylum claim. | Categorical | Different RSD procedure levels/types |
| 5 | `Tota pending start-year` | Number of asylum applications/cases that were still pending at the beginning of the year. | Numeric | Number of pending cases |
| 6 | `of which UNHCR-assisted(start-year)` | Number of cases pending at the beginning of the year that were assisted or handled with UNHCR involvement. | Numeric | Subset of the start-year pending cases |
| 7 | `Applied during year` | Number of new asylum applications submitted during the year. | Numeric | Number of applications |
| 8 | `decisions_recognized` | Number of asylum cases during the year in which refugee status was recognized. | Numeric | Recognized cases |
| 9 | `decisions_other` | Number of decisions made during the year that resulted in an outcome other than recognition or rejection. | Numeric | Other decisions |
| 10 | `Rejected` | Number of asylum applications rejected during the year. | Numeric | Rejected cases |
| 11 | `Otherwise closed` | Number of asylum cases closed during the year for reasons other than recognition or rejection. | Numeric | Withdrawn, discontinued, or otherwise closed cases |
| 12 | `Total decisions` | Total number of asylum cases for which a decision was made during the year. | Numeric | Usually combines recognized, rejected, other, and otherwise closed cases |
| 13 | `Total pending end-year` | Number of asylum cases that remained pending at the end of the year. | Numeric | Pending cases carried into the following year |
| 14 | `of which UNHCR-assisted(end-year)` | Number of cases pending at the end of the year that were assisted or handled with UNHCR involvement. | Numeric | Subset of the end-year pending cases |

# Data Exploration

In [68]:
df.head()

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5.0,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186.0,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250.0,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273.0,150,0

#### 1- Check Data Types

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129720 entries, 0 to 129719
Data columns (total 14 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Year                                     129720 non-null  int64
 1   Country / territory of asylum/residence  129720 non-null  object
 2   Origin                                   129720 non-null  object
 3   RSD procedure type / level               129719 non-null  object
 4   Tota pending start-year                  124578 non-null  object
 5   of which UNHCR-assisted(start-year)      118962 non-null  object
 6   Applied during year                      126222 non-null  object
 7   decisions_recognized                     119886 non-null  object
 8   decisions_other                          114974 non-null  object
 9   Rejected                                 121615 non-null  object
 10  Otherwise closed                         120850 non-null  object
 11  Total decisions                          97082 non-null   object
 12  Total pending end-year                   125832 non-null  object
 13  of which UNHCR-assisted(end-year)        121883 non-null  object
dtypes: int64(1), object(13)
memory usage: 13.9+ MB

#### 2- Check summary statistics of numerical columns

In [70]:
df.describe()

                Year
count  129720.000000
mean     2009.053500
std         4.877886
min      2000.000000
25%      2005.000000
50%      2010.000000
75%      2013.000000
max      2016.000000

#### 3- Check summary statistics of categorical columns

In [71]:
df.describe(include= ['object'])

,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
count,129720,129720,129719,124578,118962,126222,119886,114974,121615,120850,97082.0,125832,121883
unique,190,222,26,3763,1681,4402,1829,1085,2865,2001,4328.0,3968,1746
top,United States of America,Somalia,G / FI,0,0,0,0,0,0,0,1.0,0,0
freq,5676,2222,59432,27660,54761,15102,43299,56015,26209,35595,10218.0,25763,54039

#### 4- Check Duplicates

In [72]:
df.duplicated().sum()

np.int64(0)

#### 5- Check Missing Values

In [73]:
df.isna().sum()

Year                                           0
Country / territory of asylum/residence        0
Origin                                         0
RSD procedure type / level                     1
Tota pending start-year                     5142
of which UNHCR-assisted(start-year)        10758
Applied during year                         3498
decisions_recognized                        9834
decisions_other                            14746
Rejected                                    8105
Otherwise closed                            8870
Total decisions                            32638
Total pending end-year                      3888
of which UNHCR-assisted(end-year)           7837
dtype: int64

In [74]:
# Check missing values by percentage

df.isna().mean().round(2) * 100

Year                                        0.0
Country / territory of asylum/residence     0.0
Origin                                      0.0
RSD procedure type / level                  0.0
Tota pending start-year                     4.0
of which UNHCR-assisted(start-year)         8.0
Applied during year                         3.0
decisions_recognized                        8.0
decisions_other                            11.0
Rejected                                    6.0
Otherwise closed                            7.0
Total decisions                            25.0
Total pending end-year                      3.0
of which UNHCR-assisted(end-year)           6.0
dtype: float64

# Data Cleaning

In [75]:
df.head()

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5.0,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186.0,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250.0,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273.0,150,0

- In depth check for categorical columns

In [76]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['Country / territory of asylum/residence', 'Origin',
       'RSD procedure type / level', 'Tota pending start-year',
       'of which UNHCR-assisted(start-year)', 'Applied during year',
       'decisions_recognized', 'decisions_other', 'Rejected',
       'Otherwise closed', 'Total decisions', 'Total pending end-year',
       'of which UNHCR-assisted(end-year)'],
      dtype='object')

In [77]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

Country / territory of asylum/residence
190
['Zimbabwe' 'South Africa' 'Uzbekistan' 'United States of America'
 'Ukraine' 'Turkey' 'Turkmenistan' 'Tajikistan' 'Thailand'
 'Syrian Arab Rep.' 'Sweden' 'Slovenia' 'Slovakia'
 'Serbia and Kosovo (S/RES/1244 (1999))' 'Russian Federation' 'Romania'
 'Portugal' 'Poland' 'Nepal' 'Norway' 'Netherlands' 'Malaysia'
 'Mozambique' 'The former Yugoslav Republic of Macedonia' 'Mexico'
 'Rep. of Moldova' 'Luxembourg' 'Lithuania' 'Sri Lanka' 'Lebanon' 'Kuwait'
 'Cambodia' 'Kyrgyzstan' 'Kenya' 'Kazakhstan' 'Japan' 'Jordan' 'Italy'
 'Iceland' 'Iran (Islamic Rep. of)' 'Ireland' 'India' 'Indonesia'
 'Hungary' 'Croatia' 'China, Hong Kong SAR' 'Greece' 'United Kingdom'
 'France' 'Finland' 'Ethiopia' 'Estonia' 'Spain' 'Egypt' 'Denmark'
 'Germany' 'Czech Rep.' 'Cyprus' 'Cuba' 'China' 'Switzerland' 'Canada'
 'Belarus' 'Bosnia and Herzegovina' 'Bulgaria' 'Bangladesh' 'Belgium'
 'Azerbaijan' 'Austria' 'Australia' 'Argentina' 'United Arab Emirates'
 'Albania' 'Zambia' 'Somalia' 'Senegal' 'Rwanda' 'Panama' 'Nigeria'
 'Malta' 'Ghana' 'Gabon' 'Congo' 'Dem. Rep. of the Congo' 'Chile'
 'Central African Rep.' 'Botswana' 'Brazil' 'Benin'
 'Bolivia (Plurinational State of)' 'Israel' 'Pakistan' 'Armenia' 'Yemen'
 'Uganda' 'Togo' 'Niger' 'Namibia' 'Malawi' 'Mali' 'Guinea' 'Algeria'
 'Cameroon' "Côte d'Ivoire" 'Burkina Faso' 'Angola' 'Libya' 'Peru'
 'Latvia' 'El Salvador' 'Singapore' 'Morocco' 'Rep. of Korea' 'Ecuador'
 'Tunisia' 'Chad' 'Mauritania' 'Liberia' 'Djibouti' 'Burundi' 'Jamaica'
 'Gambia' 'Venezuela (Bolivarian Republic of)' 'Uruguay' 'Paraguay'
 'Nicaragua' 'Honduras' 'Guatemala' 'Costa Rica' 'Dominican Rep.'
 'Colombia' 'Bahamas' 'Sudan' 'United Rep. of Tanzania' 'Saudi Arabia'
 'Philippines' 'Belize' 'Bahrain' 'Sierra Leone' 'Timor-Leste' 'Iraq'
 'Afghanistan' 'Qatar' 'Oman' 'Guinea-Bissau' 'Eritrea' 'Liechtenstein'
 'New Zealand' 'Swaziland' "Lao People's Dem. Rep." 'Papua New Guinea'
 'Georgia' 'Mongolia' 'Montenegro' 'Fiji' 'Trinidad and Tobago' 'Haiti'
 'Vanuatu' 'Saint Lucia' 'Cayman Islands' 'China, Macao SAR'
 'Saint Kitts and Nevis' 'Saint Vincent and the Grenadines'
 'British Virgin Islands' 'Palau' 'Tonga' 'Aruba' 'Curaçao'
 'Antigua and Barbuda' 'Bonaire' 'Suriname' 'Dominica' 'Grenada'
 'Sint Maarten (Dutch part)' 'Montserrat' 'Monaco' 'South Sudan'
 'Madagascar' 'Lesotho' 'Turks and Caicos Islands' 'Guyana' 'Nauru'
 'Solomon Islands' 'Barbados' 'Micronesia (Federated States of)' 'Myanmar'
 'Samoa' 'Anguilla' 'Mauritius' 'Seychelles']
----------------------------------------------------------------------------------------------------
Origin
222
['Afghanistan' 'Angola' 'Albania' 'Andorra' 'United Arab Emirates'
 'Argentina' 'Armenia' 'Antigua and Barbuda' 'Australia' 'Austria'
 'Azerbaijan' 'Burundi' 'Belgium' 'Benin' 'Burkina Faso' 'Bangladesh'
 'Bulgaria' 'Bahrain' 'Bahamas' 'Bosnia and Herzegovina' 'Belarus'
 'Belize' 'Bolivia (Plurinational State of)' 'Brazil' 'Barbados'
 'Brunei Darussalam' 'Bhutan' 'Botswana' 'Central African Rep.' 'Canada'
 'Switzerland' 'Chile' 'China' "Côte d'Ivoire" 'Cameroon'
 'Dem. Rep. of the Congo' 'Congo' 'Colombia' 'Comoros' 'Cabo Verde'
 'Costa Rica' 'Cuba' 'Cyprus' 'Czech Rep.' 'Germany' 'Djibouti' 'Dominica'
 'Denmark' 'Dominican Rep.' 'Algeria' 'Ecuador' 'Egypt' 'Eritrea'
 'Western Sahara' 'Spain' 'Estonia' 'Ethiopia' 'Finland' 'Fiji' 'France'
 'Gabon' 'United Kingdom' 'Georgia' 'Ghana' 'Gibraltar' 'Guinea' 'Gambia'
 'Guinea-Bissau' 'Equatorial Guinea' 'Greece' 'Grenada' 'Guatemala'
 'Guyana' 'China, Hong Kong SAR' 'Honduras' 'Croatia' 'Haiti' 'Hungary'
 'Indonesia' 'India' 'Ireland' 'Iran (Islamic Rep. of)' 'Iraq' 'Iceland'
 'Israel' 'Italy' 'Jamaica' 'Jordan' 'Japan' 'Kazakhstan' 'Kenya'
 'Kyrgyzstan' 'Cambodia' 'Kiribati' 'Saint Kitts and Nevis'
 'Rep. of Korea' 'Kuwait' "Lao People's Dem. Rep." 'Lebanon' 'Liberia'
 'Libya' 'Saint Lucia' 'Sri Lanka' 'Lesotho' 'Lithuania' 'Luxembourg'
 'Latvia' 'China, Macao SAR' 'Morocco' 'Rep. of Moldova' 'Madagascar'
 'Maldives' 'Mexico' 'The former Yugoslav Republic of Macedonia' 'Mali'
 'Malta' 'Myanmar' 'Mongolia' 'Mozambique' 'Mauritania' 'Mauritius'
 'Malawi' 'Malaysia' 'Namibia' 'Niger' 'Nigeria' 'Nicaragua' 'Netherlands'
 'Norway' 'Nepal' 'New Zealand' 'Oman' 'Pakistan' 'Panama' 'Peru'
 'Philippines' 'Palau' 'Papua New Guinea' 'Poland'
 "Dem. People's Rep. of Korea" 'Portugal' 'Paraguay' 'Palestinian' 'Qatar'
 'Romania' 'Russian Federation' 'Rwanda' 'Saudi Arabia' 'Sudan' 'Senegal'
 'Singapore' 'Solomon Islands' 'Sierra Leone' 'El Salvador' 'San Marino'
 'Somalia' 'Serbia and Kosovo (S/RES/1244 (1999))' 'Sao Tome and Principe'
 'Suriname' 'Slovakia' 'Slovenia' 'Sweden' 'Swaziland' 'Seychelles'
 'Syrian Arab Rep.' 'Chad' 'Togo' 'Thailand' 'Tajikistan' 'Turkmenistan'
 'Timor-Leste' 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Tuvalu'
 'United Rep. of Tanzania' 'Uganda' 'Ukraine' 'Uruguay'
 'United States of America' 'Uzbekistan'
 'Saint Vincent and the Grenadines' 'Venezuela (Bolivarian Republic of)'
 'Viet Nam' 'Vanuatu' 'Samoa' 'Stateless' 'Various/Unknown' 'Yemen'
 'South Africa' 'Zambia' 'Zimbabwe' 'Nauru' 'Tibetan' 'Bermuda'
 'Cayman Islands' 'Micronesia (Federated States of)' 'Liechtenstein'
 'Monaco' 'Marshall Islands' 'Niue' 'Turks and Caicos Islands'
 'Puerto Rico' 'French Polynesia' 'New Caledonia' 'Holy See (the)'
 'Montenegro' 'French Guiana' 'Cook Islands' 'Aruba' 'South Sudan'
 'British Virgin Islands' 'Curaçao' 'Guadeloupe'
 'Saint-Pierre-et-Miquelon' 'Wallis and Futuna Islands ' 'Martinique'
 'Svalbard and Jan Mayen' 'Anguilla' 'American Samoa' 'Norfolk Island']
----------------------------------------------------------------------------------------------------
RSD procedure type / level
26
['G / FI' 'U / FI' 'G / EO' 'G / IN' 'U / AR' 'G / AR' 'G / JR' 'G / FA'
 'G / TR' 'G / BL' 'G / RA' 'G / NA' 'G / CA' 'U / FA' 'J / FI' 'G / fi'
 'U / JR' 'G / ar' 'J / AR' 'U / RA' 'J / FA' 'G / SP' 'J / RA' 'G / TP'
 'G / TA' 'U / NA' nan]
----------------------------------------------------------------------------------------------------
Tota pending start-year
3763
[0 8 265 ... '3183' '897' '41238']
----------------------------------------------------------------------------------------------------
of which UNHCR-assisted(start-year)
1681
[0 1 265 ... '897' '637' '4124']
----------------------------------------------------------------------------------------------------
Applied during year
4402
[5 0 2156 ... '910' '1039' '7964']
----------------------------------------------------------------------------------------------------
decisions_recognized
1829
[5 0 747 ... '8285' '7181' '295']
----------------------------------------------------------------------------------------------------
decisions_other
1085
[0 1 44 ... '2950' '5032' '300']
----------------------------------------------------------------------------------------------------
Rejected
2865
[0 112 31 ... '9351' '4838' '7869']
----------------------------------------------------------------------------------------------------
Otherwise closed
2001
[0 327 68 ... '675' '160141' '254801']
----------------------------------------------------------------------------------------------------
Total decisions
4328
[5.0 nan 1186.0 ... '160141' '255061' '7942']
----------------------------------------------------------------------------------------------------
Total pending end-year
3968
[0 8 1235 ... '5475' '1675' '41260']
----------------------------------------------------------------------------------------------------
of which UNHCR-assisted(end-year)
1746
[0 1235 46 ... '5475' '1152' '1675']
----------------------------------------------------------------------------------------------------

In [78]:
# Correct column name

df = df.rename(columns= {'Tota pending start-year' : 'Total pending start-year'})
df.head()

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Total pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5.0,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186.0,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250.0,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273.0,150,0

- convert datatype for columns (object --> float):

In [79]:
df['Applied during year'] = df['Applied during year'].replace('*', np.nan)
df['Applied during year'] = pd.to_numeric(df['Applied during year'])

In [80]:
num_cols = ['Total pending start-year','of which UNHCR-assisted(start-year)', 'Applied during year',	'decisions_recognized',
                'decisions_other','Rejected',	'Otherwise closed',	'Total decisions',	'Total pending end-year','of which UNHCR-assisted(end-year)']

for col in num_cols:
    df[col] = df[col].replace('*', np.nan)
    df[col] = pd.to_numeric(df[col])

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129720 entries, 0 to 129719
Data columns (total 14 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   Year                                     129720 non-null  int64
 1   Country / territory of asylum/residence  129720 non-null  object
 2   Origin                                   129720 non-null  object
 3   RSD procedure type / level               129719 non-null  object
 4   Total pending start-year                 121547 non-null  float64
 5   of which UNHCR-assisted(start-year)      117641 non-null  float64
 6   Applied during year                      122863 non-null  float64
 7   decisions_recognized                     118406 non-null  float64
 8   decisions_other                          114350 non-null  float64
 9   Rejected                                 119318 non-null  float64
 10  Otherwise closed                         118486 non-null  float64
 11  Total decisions                          93873 non-null   float64
 12  Total pending end-year                   122918 non-null  float64
 13  of which UNHCR-assisted(end-year)        120540 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 13.9+ MB

- In depth check for Numerical columns

In [82]:
num_cols = df.select_dtypes(include= 'number').columns
num_cols

Index(['Year', 'Total pending start-year',
       'of which UNHCR-assisted(start-year)', 'Applied during year',
       'decisions_recognized', 'decisions_other', 'Rejected',
       'Otherwise closed', 'Total decisions', 'Total pending end-year',
       'of which UNHCR-assisted(end-year)'],
      dtype='object')

In [83]:
#for col in num_cols:

    #px.histogram(data_frame= df, x= col, title= col).show()
    #px.box(data_frame= df, x= col, title= col).show()

In [84]:
# Drop Nan rows from columns ---> Low Nan %

df.dropna(subset= ['Total pending start-year', 'of which UNHCR-assisted(start-year)','Applied during year',
                  'decisions_recognized', 'Rejected','Otherwise closed','decisions_other',                           
                  'Total pending end-year','of which UNHCR-assisted(end-year)'], ignore_index= True, inplace= True)

In [85]:
# Check duplicates after removing any column

df.duplicated().sum()

np.int64(0)

In [86]:
# Check missing values by percentage

df.isna().mean().round(2) * 100

Year                                        0.0
Country / territory of asylum/residence     0.0
Origin                                      0.0
RSD procedure type / level                  0.0
Total pending start-year                    0.0
of which UNHCR-assisted(start-year)         0.0
Applied during year                         0.0
decisions_recognized                        0.0
decisions_other                             0.0
Rejected                                    0.0
Otherwise closed                            0.0
Total decisions                            24.0
Total pending end-year                      0.0
of which UNHCR-assisted(end-year)           0.0
dtype: float64

In [87]:
df[num_cols]

,Year,Total pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,0.0,0.0,5.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0
1,2000,8.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,8.0,0.0
2,2000,265.0,265.0,2156.0,747.0,0.0,112.0,327.0,1186.0,1235.0,1235.0
3,2000,196.0,0.0,225.0,151.0,0.0,31.0,68.0,250.0,171.0,0.0
4,2000,193.0,0.0,218.0,182.0,0.0,51.0,40.0,273.0,150.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
110659,2016,17.0,17.0,43.0,0.0,25.0,0.0,37.0,62.0,23.0,23.0
110660,2016,75.0,0.0,79.0,0.0,11.0,49.0,6.0,66.0,68.0,0.0
110661,2016,23.0,0.0,24.0,0.0,0.0,18.0,0.0,18.0,9.0,0.0
110662,2016,130.0,0.0,71.0,37.0,0.0,27.0,0.0,64.0,82.0,0.0
110663,2016,475.0,0.0,299.0,31.0,19.0,223.0,15.0,288.0,361.0,0.0

 - Fill NAN numeric columns by using (KNNImputer)

In [ ]:
from sklearn.impute import KNNImputer

knn = KNNImputer()
knn_arr = knn.fit_transform(df[num_cols])
knn_arr

In [ ]:
from sklearn.impute import KNNImputer

knn = KNNImputer()

df[num_cols] = knn.fit_transform(df[num_cols])

# Data Analysis

In [146]:
df.head()

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Total pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0.0,0.0,5.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0
1,2000,South Africa,Afghanistan,G / FI,8.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,8.0,0.0
2,2000,Uzbekistan,Afghanistan,U / FI,265.0,265.0,2156.0,747.0,0.0,112.0,327.0,1186.0,1235.0,1235.0
3,2000,United States of America,Afghanistan,G / EO,196.0,0.0,225.0,151.0,0.0,31.0,68.0,250.0,171.0,0.0
4,2000,United States of America,Afghanistan,G / IN,193.0,0.0,218.0,182.0,0.0,51.0,40.0,273.0,150.0,0.0

#### Univariate

### Q: How are asylum applications distributed across years?

In [149]:
px.histogram(data_frame= df, x='Year' , y='Applied during year', text_auto= True, title= 'Total_Application_Year', nbins= 50)

In [92]:
px.box(data_frame= df, x= 'Year')

## Q: What is the Percentage for Recognition & Rejection

In [ ]:
decision_outcomes = pd.DataFrame({'Outcome': ['Recognized', 'Rejected'],
                                 'Count': [df['decisions_recognized'].sum(),
                                  df['Rejected'].sum()]})

In [125]:
px.pie(decision_outcomes,
    names='Outcome', values='Count',
    hole=0.5, title='Asylum Decision Outcomes')

#### Bivariate

###  Q: Does the number of applications increase or decrease over time?

In [108]:
application_o_time = df.groupby('Year')[['Applied during year', 'Total decisions', 'Total pending end-year']].sum().reset_index()
application_o_time

    Year  Applied during year  Total decisions  Total pending end-year
0   2000            1093045.0        1090346.0                947926.0
1   2001             918156.0         936260.0                943979.0
2   2002             948536.0        1010189.0               1093823.0
3   2003             840236.0        1003439.0                995812.0
4   2004             681159.0         887490.0                885186.0
5   2005             674005.0         830469.0                802153.0
6   2006             607461.0         692008.0                739142.0
7   2007             643465.0         645072.0                738641.0
8   2008             864942.0         702231.0                824905.0
9   2009             935603.0         761555.0                988514.0
10  2010             830964.0         725430.0                830846.0
11  2011             864232.0         766917.0                896646.0
12  2012             923155.0         903053.0                942597.0
13  2013            1061074.0         879758.0               1164274.0
14  2014            1616565.0        1378629.0               1700542.0
15  2015            1031864.0         655578.0                744944.0
16  2016             293639.0         233244.0                270673.0

In [109]:
px.line(data_frame= application_o_time, x= 'Year', y= ['Applied during year', 'Total decisions', 'Total pending end-year'],
       title= 'Applications_Over_Time')

### Q: Which asylum/residence countries have the highest number of applications?
          (Top Asylum-Hosting Countries)

In [130]:
highest_asylum_Hosting = (df.groupby('Country / territory of asylum/residence')['Applied during year']
                        .sum().sort_values(ascending=False).reset_index().head(10))
highest_asylum_Hosting

  Country / territory of asylum/residence  Applied during year
0                                 Germany            1552188.0
1                                  France            1269189.0
2                            South Africa            1256673.0
3                          United Kingdom            1070121.0
4                United States of America            1030417.0
5                                  Sweden             753029.0
6                      Russian Federation             488686.0
7                                 Belgium             446036.0
8                                   Italy             424516.0
9                                  Canada             407510.0

In [107]:
px.pie(data_frame= highest_asylum_Hosting, names= 'Country / territory of asylum/residence', 
       values= 'Applied during year',
       title= 'Top Asylum-Hosting Countries',
       hole= 0.3)

### Q: Which origins are most frequently represented?

In [128]:
top_origin = (df.groupby('Origin')['Applied during year']
        .sum()
        .sort_values(ascending=False)
        .head(10)
        .reset_index())
top_origin

                                  Origin  Applied during year
0                            Afghanistan             964951.0
1                        Various/Unknown             886935.0
2                                   Iraq             805683.0
3                 Dem. Rep. of the Congo             634620.0
4                               Zimbabwe             629160.0
5                       Syrian Arab Rep.             610904.0
6  Serbia and Kosovo (S/RES/1244 (1999))             605660.0
7                                Somalia             566600.0
8                                Ukraine             539081.0
9                                Eritrea             464876.0

In [129]:
px.bar(data_frame=top_origin,
       x='Origin',
       y='Applied during year',
    title='Top 10 Countries of Origin')

### Q: Is there a relationship between applications and pending cases?

In [ ]:
df_corr = df[['Applied during year', 'Total pending end-year']].corr()
df_corr

                        Applied during year  Total pending end-year
Applied during year                1.000000                0.196349
Total pending end-year             0.196349                1.000000

In [ ]:
px.imshow(df_corr, text_auto= True)

### Multivariate

### Q: Does the number of decisions & rejecting keep up with applications?

In [131]:
df_filtered =  df.groupby('Year')[['Applied during year', 
                                         'Total decisions','Total pending end-year',
                                           'decisions_recognized','Rejected']].sum().reset_index()

In [135]:
px.bar(data_frame= df_filtered, x= 'Rejected',
       y='decisions_recognized', color= 'Year',
       title='Asylum Decisions by Outcome',
       barmode= 'group')

### Q: how asylum applications and outcomes changed over time for different countries of origin.

In [ ]:
origin_year = (df.groupby(['Year', 'Origin'])['Applied during year']
                .sum().head(10)
                .reset_index())

origin_year

   Year               Origin  Applied during year
0  2000          Afghanistan             291283.0
1  2000              Albania               9765.0
2  2000              Algeria              10312.0
3  2000              Andorra                  1.0
4  2000               Angola               7160.0
5  2000  Antigua and Barbuda                  7.0
6  2000            Argentina               1631.0
7  2000              Armenia              10726.0
8  2000            Australia                  9.0
9  2000              Austria                 13.0

In [ ]:
px.bar(data_frame= origin_year, x= 'Origin', y= 'Year',
       color= 'Applied during year',
       barmode= 'group', 
       text_auto= True)

### Q: Which countries have the largest pending asylum caseload?

In [ ]:
country_pending = (df.groupby('Country / territory of asylum/residence')[['Applied during year',
                    'Total decisions', 'Total pending end-year',
                      'decisions_recognized', 'Rejected']].sum().head(10)).sort_values('Total pending end-year', ascending=False).reset_index()
country_pending

,Country / territory of asylum/residence,Applied during year,Total decisions,Total pending end-year,decisions_recognized,Rejected
0,Austria,309559.0,308967.0,434863.0,45791.0,108478.0
1,Australia,207383.0,194185.0,129697.0,54259.0,129799.0
2,Angola,19876.0,7619.0,95457.0,2134.0,1460.0
3,Argentina,9391.0,9313.0,16681.0,1661.0,4294.0
4,Algeria,13276.0,8820.0,13871.0,275.0,4864.0
5,Albania,1185.0,783.0,1179.0,105.0,56.0
6,Armenia,2986.0,2902.0,1143.0,869.0,305.0
7,Afghanistan,623.0,585.0,425.0,152.0,236.0
8,Aruba,9.0,3.0,21.0,1.0,0.0
9,Antigua and Barbuda,1.0,2.0,1.0,1.0,0.0

In [ ]:
px.bar(data_frame= country_pending,
    x='Country / territory of asylum/residence',
    y='Total pending end-year',
    title='Total pending end-year')

# Deployment

In [ ]:
# save cleaned dataframe

df.to_csv('cleaned_df.csv', index= False)

In [ ]:
df.head()

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Total pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0.0,0.0,5.0,5.0,0.0,0.0,0.0,5.0,0.0,0.0
1,2000,South Africa,Afghanistan,G / FI,8.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,8.0,0.0
2,2000,Uzbekistan,Afghanistan,U / FI,265.0,265.0,2156.0,747.0,0.0,112.0,327.0,1186.0,1235.0,1235.0
3,2000,United States of America,Afghanistan,G / EO,196.0,0.0,225.0,151.0,0.0,31.0,68.0,250.0,171.0,0.0
4,2000,United States of America,Afghanistan,G / IN,193.0,0.0,218.0,182.0,0.0,51.0,40.0,273.0,150.0,0.0

In [ ]:
import streamlit as st

In [126]:
! streamlit run Home.py

^C

In [150]:
import pipreqs
! pipreqs ./

INFO: Not scanning for jupyter notebooks.
WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.5" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "plotly" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "plotly" was resolved to "plotly:6.9.0" package (https://pypi.org/project/plotly/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in ./requirements.txt